workflows:
  android-capacitor-build:
    name: SCMS Android APK Build
    max_build_duration: 15
    instance_type: mac_mini_m2
    environment:
      node: 24
    scripts:
      - name: Create www Folder and Copy Files
        script: |
          mkdir -p www
          cp -r js index.html style.css www/
      - name: Install Dependencies
        script: npm install
      - name: Install Capacitor Core
        script: npm install @capacitor/cli @capacitor/core @capacitor/android
      - name: Add Android Platform if missing
        script: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi
      - name: Sync Directly to Android
        script: npx cap sync android
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
